In [1]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv('zomato.csv',encoding='latin-1')
data.shape

(9551, 21)

In [6]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [7]:
data.drop(columns=['Restaurant ID','Is delivering now'],inplace=True)

In [8]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Switch to order menu', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [9]:
data['Country Code'].nunique()

15

In [67]:
data['Country Code'].value_counts()

1      8652
216     434
215      80
214      60
30       60
189      60
148      40
208      34
14       24
162      22
94       21
191      20
166      20
184      20
37        4
Name: Country Code, dtype: int64

In [68]:
mask=data['Country Code']==1
data=data[mask]

In [10]:

data.drop(columns=['Country Code','Currency'],inplace=True)

In [11]:
data.columns

Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [12]:
data['City'].nunique()

141

In [13]:
mask=data['City'].isin(['New Delhi','Gurgaon','Noida'])
data=data[mask]
data.shape

(7671, 17)

In [14]:
data.columns

Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [15]:

data.drop(columns=['Restaurant Name','Address','Locality','Locality Verbose','Rating color','Rating text',],inplace=True)

In [75]:
data['Switch to order menu']

1161    No
1162    No
1163    No
1164    No
1165    No
1166    No
1167    No
1168    No
1169    No
1170    No
1171    No
1172    No
1173    No
1174    No
1175    No
1176    No
1177    No
1178    No
1179    No
1180    No
1181    No
1182    No
1183    No
1184    No
1185    No
1186    No
1187    No
1188    No
1189    No
1190    No
        ..
9083    No
9084    No
9085    No
9086    No
9087    No
9088    No
9089    No
9090    No
9091    No
9092    No
9093    No
9094    No
9095    No
9096    No
9097    No
9098    No
9099    No
9100    No
9101    No
9102    No
9103    No
9104    No
9105    No
9106    No
9107    No
9108    No
9109    No
9110    No
9111    No
9112    No
Name: Switch to order menu, Length: 7671, dtype: object

In [16]:

data.drop(columns=['Switch to order menu'],inplace=True)

In [17]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [78]:
data['Cuisines'].value_counts()>50

North Indian                                                       True
North Indian, Chinese                                              True
Fast Food                                                          True
Chinese                                                            True
North Indian, Mughlai                                              True
Cafe                                                               True
Bakery                                                             True
North Indian, Mughlai, Chinese                                     True
Bakery, Desserts                                                   True
Street Food                                                        True
Pizza, Fast Food                                                   True
Chinese, Fast Food                                                 True
Mithai, Street Food                                                True
South Indian                                                    

In [18]:
data['Has Table booking'].replace('Yes',1,inplace=True)
data['Has Table booking'].replace('No',0,inplace=True)

In [19]:
data['Has Table booking'].value_counts()

0    6640
1    1031
Name: Has Table booking, dtype: int64

In [20]:
data['Has Online delivery'].replace('Yes',1,inplace=True)
data['Has Online delivery'].replace('No',0,inplace=True)

In [21]:
data['Has Online delivery'].value_counts()

0    5393
1    2278
Name: Has Online delivery, dtype: int64

In [22]:
data.corr()['Average Cost for two']


Longitude               0.071854
Latitude                0.070816
Average Cost for two    1.000000
Has Table booking       0.643845
Has Online delivery     0.072198
Price range             0.848425
Aggregate rating        0.329785
Votes                   0.297741
Name: Average Cost for two, dtype: float64

In [23]:
data.drop(columns=['Longitude','Latitude','Has Online delivery','Price range',],inplace=True)

In [24]:
data.columns

Index(['City', 'Cuisines', 'Average Cost for two', 'Has Table booking',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [25]:
data

City                                        Cuisines  \
1161  Gurgaon                                 Cafe, Beverages   
1162  Gurgaon                           North Indian, Mughlai   
1163  Gurgaon                           North Indian, Mughlai   
1164  Gurgaon                   South Indian, Seafood, Kerala   
1165  Gurgaon                                          Bakery   
1166  Gurgaon                                       Ice Cream   
1167  Gurgaon                                         Chinese   
1168  Gurgaon                                       Fast Food   
1169  Gurgaon                         Japanese, Thai, Chinese   
1170  Gurgaon                                 Pizza, Desserts   
1171  Gurgaon                            Raw Meats, Fast Food   
1172  Gurgaon                  South Indian, Chinese, Mughlai   
1173  Gurgaon                         Fast Food, North Indian   
1174  Gurgaon                           North Indian, Chinese   
1175  Gurgaon             North Indian, South Indian, Chinese   
1176  Gurgaon                                            Cafe   
1177  Gurgaon                                       Raw Meats   
1178  Gurgaon                            Mithai, North Indian   
1179  Gurgaon                North Indian, Chinese, Fast Food   
1180  Gurgaon                                    North Indian   
1181  Gurgaon                           North Indian, Chinese   
1182  Gurgaon                       South Indian, Street Food   
1183  Gurgaon                           North Indian, Chinese   
1184  Gurgaon                           North Indian, Chinese   
1185  Gurgaon                                    North Indian   
1186  Gurgaon                  North Indian, Mughlai, Seafood   
1187  Gurgaon                                       Fast Food   
1188  Gurgaon                                        Japanese   
1189  Gurgaon              North Indian, Chinese, Continental   
1190  Gurgaon                               Bakery, Fast Food   
...       ...                                             ...   
9083    Noida                                         Italian   
9084    Noida                                            Cafe   
9085    Noida                                       Ice Cream   
9086    Noida                                         Chinese   
9087    Noida                                       Ice Cream   
9088    Noida                               Burger, Fast Food   
9089    Noida                                            Cafe   
9090    Noida                                   Chinese, Thai   
9091    Noida                                       Fast Food   
9092    Noida                                         Chinese   
9093    Noida                           Mughlai, North Indian   
9094    Noida                       Italian, Pizza, Fast Food   
9095    Noida             South Indian, North Indian, Chinese   
9096    Noida                               American, Tex-Mex   
9097    Noida                        North Indian, Rajasthani   
9098    Noida                                       Fast Food   
9099    Noida                                Italian, Chinese   
9100    Noida                                        Desserts   
9101    Noida                             Desserts, Ice Cream   
9102    Noida                                            Cafe   
9103    Noida                  Continental, Lebanese, Mexican   
9104    Noida  Chinese, North Indian, South Indian, Fast Food   
9105    Noida              North Indian, Continental, Chinese   
9106    Noida                           North Indian, Mughlai   
9107    Noida                           North Indian, Chinese   
9108    Noida                           North Indian, Chinese   
9109    Noida                                       Fast Food   
9110    Noida                                       Fast Food   
9111    Noida                           North Indian, Chinese   
9112    Noida                            Raw

In [26]:
cuisine=data.groupby('Cuisines')['Average Cost for two'].mean().reset_index()

In [27]:
new_data=data.merge(cuisine,on='Cuisines')

In [28]:
new_data.drop(columns=['Cuisines'],inplace=True)

In [29]:
new_data.head(2)

City  Average Cost for two_x  Has Table booking  Aggregate rating  \
0    Gurgaon                     350                  0               3.4   
1  New Delhi                     200                  0               0.0   

   Votes  Average Cost for two_y  
0     16              416.666667  
1      0              416.666667

In [30]:
new_data.rename(columns={'Average Cost for two_x':'cost','Average Cost for two_y':'Cuisine_name'},inplace=True)

In [31]:
new_data.head(2)

City  cost  Has Table booking  Aggregate rating  Votes  Cuisine_name
0    Gurgaon   350                  0               3.4     16    416.666667
1  New Delhi   200                  0               0.0      0    416.666667

In [32]:
new_data=new_data[['City','Has Table booking','Aggregate rating','Votes','Cuisine_name']]

In [33]:
new_data.head(2)

City  Has Table booking  Aggregate rating  Votes  Cuisine_name
0    Gurgaon                  0               3.4     16    416.666667
1  New Delhi                  0               0.0      0    416.666667

In [34]:
X=new_data.iloc[:,:-1].values
y=new_data.iloc[:, -1].values
y

array([ 416.66666667,  416.66666667,  416.66666667, ...,  450.        ,
       1000.        ,  450.        ])

In [35]:

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [36]:
X[:, 0]=encoder.fit_transform(X[:, 0])
X

array([[0, 0, 3.4, 16],
       [1, 0, 0.0, 0],
       [1, 0, 4.1, 92],
       ...,
       [2, 0, 3.5, 105],
       [2, 1, 0.0, 0],
       [2, 0, 2.0, 161]], dtype=object)

In [37]:
from sklearn.preprocessing import OneHotEncoder
oencoder=OneHotEncoder(categorical_features=[0])


In [38]:
X=oencoder.fit_transform(X).toarray()

In [39]:
X.shape

(7671, 6)

In [40]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)

C:\Users\satyam swet\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [41]:
X_train.shape

(6136, 6)

In [42]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()

In [43]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [44]:
y_pred=regressor.predict(X_test)

In [45]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.41472472886112755

In [46]:
from sklearn.ensemble import RandomForestRegressor
regressor1=RandomForestRegressor(n_estimators=200)

C:\Users\satyam swet\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [47]:
regressor1.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [48]:
y_pred1=regressor1.predict(X_test)

In [49]:
r2_score(y_test,y_pred1)

0.2397832891125281

In [52]:
from sklearn.tree import DecisionTreeRegressor
regressor2=DecisionTreeRegressor()

In [53]:
y_pred2=regressor2.predict(X_test)

NotFittedError: This DecisionTreeRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:
from sklearn.svm import SVR
reg3=SVR()

In [141]:
ypred3=reg3.predict(X_test)

NotFittedError: This SVR instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [142]:
regressor.intercept_

431.98315134047516

In [143]:
regressor.coef_

array([-2.40981376e+01,  2.40981376e+01, -1.09540539e+01, -1.31440838e+01,
        7.09558206e+02,  3.45937938e+01,  1.95546925e-01])

In [144]:
X_test

array([[  1. ,   0. ,   1. , ...,   0. ,   3. ,  11. ],
       [  1. ,   0. ,   1. , ...,   1. ,   3.5,  18. ],
       [  1. ,   0. ,   1. , ...,   0. ,   3. ,  13. ],
       ...,
       [  1. ,   0. ,   1. , ...,   1. ,   3.6, 392. ],
       [  1. ,   0. ,   0. , ...,   0. ,   3.4,  22. ],
       [  0. ,   1. ,   0. , ...,   0. ,   3.8,  46. ]])

In [145]:
y_test[0]

330.88235294117646

In [151]:
regressor.predict(X_test[221].reshape(1,7))

array([496.59170466])